version: "3.0"
services:
  edc:
    container_name: edc
    image: "julianlegler/edc_blockchain_catalog"
    ports:
      - "8181:8181"
      - "8182:8182"
      - "8282:8282"
    environment:
      - EDC_BLOCKCHAIN_INTERFACE_URL=http://edc-interface:3000
      - IDS_WEBHOOK_ADDRESS=http://edc:8282
  edc-interface:
    container_name: edc-interface
    image: johann1999/edc-interface:linux-amd64
    ports:
      - "3000:3000"
    environment:
      - PINATA_KEY=pinata_key
  data-dashboard:
    container_name: data-dashboard
    image: johann1999/data-dashboard:linux-amd64
    ports:
      - "5500:80"